<?php

namespace Charlestown\OperationBundle\Entity;

/**
 * OperationApplianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationApplianceRepository extends \Doctrine\ORM\EntityRepository
{
}
