<?php

namespace Charlestown\OperationBundle\Entity;

/**
 * TimeslotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeslotRepository extends \Doctrine\ORM\EntityRepository
{
}
