<?php

namespace Charlestown\DemandBundle\Entity;

/**
 * DemandMobilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandMobilityRepository extends \Doctrine\ORM\EntityRepository
{
}
