<?php

namespace Charlestown\DemandBundle\Entity;

/**
 * DemandVacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandVacancyRepository extends \Doctrine\ORM\EntityRepository
{
}
