<?php

namespace Charlestown\DemandBundle\Entity;

/**
 * DemandMeetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandMeetingRepository extends \Doctrine\ORM\EntityRepository
{
}
