<?php

namespace Charlestown\NotificationBundle\Entity;

/**
 * NotificationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationUserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNotificationByUser($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select n
                    From CharlestownNotificationBundle:NotificationUser n
                    WHERE n.user = ?1');

        $query->setParameter(1,$id);

        return $query->getResult();
    }

    public function getNotificationByUserAndNotification($id, $notificationId){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select n
                    From CharlestownNotificationBundle:NotificationUser n
                    WHERE n.user = ?1
                     AND n.notification > ?2');

        $query->setParameter(1,$id);
        $query->setParameter(2,$notificationId);

        return $query->getResult();
    }
}
