services:
    sonata.block.service.mailer:
        class: Charlestown\CoreBundle\Services\MailerBlock
        arguments:
            - sonata.block.service.mailer
            - @templating
        tags:
            - { name: sonata.block }

    admin.operation:
        class: Charlestown\CoreBundle\Admin\OperationAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\Operation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Opération, group: Event }
    admin.devis:
        class: Charlestown\CoreBundle\Admin\DevisAdmin
        arguments: [~, Charlestown\CustomerBundle\Entity\Devis, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Devis, group: Client }
    admin.demand_formation:
        class: Charlestown\CoreBundle\Admin\DemandFormationAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandFormation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Formation, group: Demande }
    admin.customer:
        class: Charlestown\CoreBundle\Admin\CustomerAdmin
        arguments: [~, Charlestown\CustomerBundle\Entity\Customer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Client, group: Admin }
    admin.collaborator:
        class: Charlestown\CoreBundle\Admin\CollaboratorAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\Collaborator, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Collaborateur, group: Admin }
    admin.agency:
        class: Charlestown\CoreBundle\Admin\AgencyAdmin
        arguments: [~, Charlestown\AgencyBundle\Entity\Agency, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Agence, group: Admin }
    admin.file:
        class: Charlestown\CoreBundle\Admin\FileAdmin
        arguments: [~, Charlestown\FileBundle\Entity\File, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Fichier, group: Divers }
    admin.file_type:
        class: Charlestown\CoreBundle\Admin\FileTypeAdmin
        arguments: [~, Charlestown\FileBundle\Entity\FileType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Type de fichier, group: Divers }
    admin.demand_meeting:
        class: Charlestown\CoreBundle\Admin\DemandMeetingAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandMeeting, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rendez-vous, group: Demande }
    admin.demand_vacancy:
        class: Charlestown\CoreBundle\Admin\DemandVacancyAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandVacancy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Congés, group: Demande }
    admin.demand_mobility:
        class: Charlestown\CoreBundle\Admin\DemandMobilityAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandMobility, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Mobilité, group: Demande }
    admin.operation_appliance:
        class: Charlestown\CoreBundle\Admin\OperationApplianceAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\OperationAppliance, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Candidatures, group: Event }
    admin.file_operation:
        class: Charlestown\CoreBundle\Admin\FileOperationAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\FileOperation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Photo, group: Event }
    admin.timeslot:
        class: Charlestown\CoreBundle\Admin\TimeslotAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\Timeslot, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Créneau, group: Event }
    admin.syndicat:
        class: Charlestown\CoreBundle\Admin\SyndicatAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\Syndicat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Syndicat, group: Admin }
    admin.mandate:
        class: Charlestown\CoreBundle\Admin\MandateAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\Mandate, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Mandat, group: Admin }
    admin.article:
        class: Charlestown\CoreBundle\Admin\ArticleAdmin
        arguments: [~, Charlestown\BlogBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Article, group: Admin }
    admin.ideaBox:
        class: Charlestown\CoreBundle\Admin\IdeaBoxAdmin
        arguments: [~, Charlestown\CoreBundle\Entity\IdeaBox, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Boite à idées, group: Admin }
    admin.book:
        class: Charlestown\CoreBundle\Admin\BookAdmin
        arguments: [~, Charlestown\CustomerBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Books event, group: Event }
    admin.message:
        class: Charlestown\CoreBundle\Admin\MessageAdmin
        arguments: [~, Charlestown\ChatBundle\Entity\Message, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Messages, group: Chat }
