services:
    admin.customer:
        class: Charlestown\CoreBundle\Admin\CustomerAdmin
        arguments: [~, Charlestown\UserBundle\Entity\Customer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Client, group: Utilisateurs }
    admin.businessSupport:
        class: Charlestown\CoreBundle\Admin\BusinessSupportAdmin
        arguments: [~, Charlestown\UserBundle\Entity\BusinessSupport, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Accueil Entreprise, group: Utilisateurs }
    admin.event:
        class: Charlestown\CoreBundle\Admin\EventAdmin
        arguments: [~, Charlestown\UserBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Event, group: Utilisateurs }