services:
    sonata.block.service.mailer:
        class: Charlestown\CoreBundle\Services\MailerBlock
        arguments:
            - sonata.block.service.mailer
            - @templating
        tags:
            - { name: sonata.block }
    admin.customer:
        class: Charlestown\CoreBundle\Admin\CustomerAdmin
        arguments: [~, Charlestown\CustomerBundle\Entity\Customer, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Client, group: Utilisateurs }
    admin.businessSupport:
        class: Charlestown\CoreBundle\Admin\BusinessSupportAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\BusinessSupport, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Accueil Entreprise, group: Utilisateurs }
    admin.event:
        class: Charlestown\CoreBundle\Admin\EventAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\Event, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Event, group: Utilisateurs }
    admin.agency:
        class: Charlestown\CoreBundle\Admin\AgencyAdmin
        arguments: [~, Charlestown\AgencyBundle\Entity\Agency, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Agence, group: Divers }
    admin.file:
        class: Charlestown\CoreBundle\Admin\FileAdmin
        arguments: [~, Charlestown\FileBundle\Entity\File, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Fichier, group: Divers }
    admin.file_type:
        class: Charlestown\CoreBundle\Admin\FileTypeAdmin
        arguments: [~, Charlestown\FileBundle\Entity\FileType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Type de fichier, group: Divers }
    admin.demand_formation:
        class: Charlestown\CoreBundle\Admin\DemandFormationAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandFormation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Formation, group: Demande }
    admin.demand_meeting:
        class: Charlestown\CoreBundle\Admin\DemandMeetingAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandMeeting, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rendez-vous, group: Demande }
    admin.demand_vacancy:
        class: Charlestown\CoreBundle\Admin\DemandVacancyAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandVacancy, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Congés, group: Demande }
    admin.demand_mobility:
        class: Charlestown\CoreBundle\Admin\DemandMobilityAdmin
        arguments: [~, Charlestown\DemandBundle\Entity\DemandMobility, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Mobilité, group: Demande }
    admin.operation:
        class: Charlestown\CoreBundle\Admin\OperationAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\Operation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Opération, group: Opérations }
    admin.operation_appliance:
        class: Charlestown\CoreBundle\Admin\OperationApplianceAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\OperationAppliance, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Candidatures, group: Opérations }
    admin.file_operation:
        class: Charlestown\CoreBundle\Admin\FileOperationAdmin
        arguments: [~, Charlestown\OperationBundle\Entity\FileOperation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Photo, group: Opérations }
    admin.syndicat:
        class: Charlestown\CoreBundle\Admin\SyndicatAdmin
        arguments: [~, Charlestown\CollaboratorBundle\Entity\Syndicat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Syndicat, group: Utilisateurs }
