<?php

namespace Charlestown\ChatBundle\Entity;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastMessages($id){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select m
                    From CharlestownChatBundle:Message m
                    WHERE m.id > ?1 ');
        $query->setParameter(1,$id);

        return $query->getResult();
    }
}
