<?php

namespace Charlestown\BlogBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastsCollaborator(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select a
                    From CharlestownBlogBundle:Article a
                    Where a.visibleCollaborator = true
                    ');

        $result = $query->getResult();

        if(sizeof($result) > 5){
            $lasts = array_slice($result,sizeof($result) - 5);
            return $lasts;
        }

        return array_reverse($result);

    }

    public function findLastsCustomer(){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select a
                    From CharlestownBlogBundle:Article a
                    Where a.visibleCustomer = true
                    ');

        $result = $query->getResult();

        if(sizeof($result) > 5){
            $lasts = array_slice($result,sizeof($result) - 5);
            return $lasts;
        }

        return array_reverse($result);

    }
}
