<?php

namespace Charlestown\AnnouncmentBundle\Entity;

/**
 * AnnouncmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncmentRepository extends \Doctrine\ORM\EntityRepository
{
}
