<?php

namespace Charlestown\CollaboratorBundle\Entity;

/**
 * BusinessSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessSupportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSyndicat(){
        $empty = "";
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'Select b
                    From CharlestownCollaboratorBundle:BusinessSupport b
                    WHERE b.syndicat != ?1 ');

        $query->setParameter(1,$empty);

        return $query->getResult();
    }
}
