<?php

namespace Charlestown\CollaboratorBundle\Entity;

/**
 * BusinessSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessSupportRepository extends \Doctrine\ORM\EntityRepository
{
}
