<?php

namespace Charlestown\CollaboratorBundle\Entity;

/**
 * MandateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MandateRepository extends \Doctrine\ORM\EntityRepository
{
}
