<?php

namespace Charlestown\FileBundle\Entity;

/**
 * FileTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByFileType($type){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                    'Select f
                    From CharlestownFileBundle:File f
                    Join f.fileType ft
                    WHERE ft.type = ?1');

        $query->setParameter(1, $type);

        return $query->getResult();
    }
}
